name: tabnavigator
version: "1.0.0"
description: A flutter widget which helps to manage the tabs on the screen. Based on streams.
repository: "https://github.com/surfstudio/flutter-tabnavigator"
issue_tracker: "https://github.com/surfstudio/flutter-tabnavigator/issues"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

flutter:
