name: tabnavigator
version: "1.0.0"
description: Module can manage the tabs on the screen.
repository: "https://github.com/surfstudio/SurfGear/tree/main/packages/tabnavigator"
issue_tracker: "https://github.com/surfstudio/SurfGear/issues"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^2.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"

flutter:
